if(NOT DEFINED OPENRCC_GRPC_SOURCE_DIR)
    message(FATAL_ERROR "OPENRCC_GRPC_SOURCE_DIR is required")
endif()

set(ABSEIL_COPTS_FILE
    "${OPENRCC_GRPC_SOURCE_DIR}/third_party/abseil-cpp/absl/copts/AbseilConfigureCopts.cmake"
)
if(NOT EXISTS "${ABSEIL_COPTS_FILE}")
    message(FATAL_ERROR "Abseil CMake copts file not found: ${ABSEIL_COPTS_FILE}")
endif()

file(READ "${ABSEIL_COPTS_FILE}" ABSEIL_COPTS_CONTENT)
set(ABSEIL_OLD_CONDITION "if(APPLE AND CMAKE_CXX_COMPILER_ID MATCHES [[Clang]])")
set(ABSEIL_PREVIOUS_CONDITION
    "if(APPLE AND CMAKE_CXX_COMPILER_ID MATCHES [[Clang]] AND NOT CMAKE_OSX_ARCHITECTURES STREQUAL \"arm64\")"
)
set(ABSEIL_NEW_CONDITION
    "if(APPLE AND CMAKE_CXX_COMPILER_ID MATCHES [[Clang]] AND NOT (CMAKE_OSX_ARCHITECTURES STREQUAL \"arm64\" OR (NOT CMAKE_OSX_ARCHITECTURES AND CMAKE_SYSTEM_PROCESSOR MATCHES \"^(arm64|aarch64)$\")))"
)

string(FIND "${ABSEIL_COPTS_CONTENT}" "${ABSEIL_NEW_CONDITION}" ABSEIL_ALREADY_PATCHED)
if(ABSEIL_ALREADY_PATCHED LESS 0)
    string(FIND "${ABSEIL_COPTS_CONTENT}" "${ABSEIL_OLD_CONDITION}" ABSEIL_CONDITION_OFFSET)
    if(ABSEIL_CONDITION_OFFSET GREATER_EQUAL 0)
        string(REPLACE "${ABSEIL_OLD_CONDITION}" "${ABSEIL_NEW_CONDITION}" ABSEIL_COPTS_CONTENT "${ABSEIL_COPTS_CONTENT}")
    else()
        string(FIND "${ABSEIL_COPTS_CONTENT}" "${ABSEIL_PREVIOUS_CONDITION}" ABSEIL_PREVIOUS_CONDITION_OFFSET)
        if(ABSEIL_PREVIOUS_CONDITION_OFFSET LESS 0)
            message(FATAL_ERROR "Expected Abseil Apple Randen condition not found in ${ABSEIL_COPTS_FILE}")
        endif()

        string(REPLACE "${ABSEIL_PREVIOUS_CONDITION}" "${ABSEIL_NEW_CONDITION}" ABSEIL_COPTS_CONTENT "${ABSEIL_COPTS_CONTENT}")
    endif()

    file(WRITE "${ABSEIL_COPTS_FILE}" "${ABSEIL_COPTS_CONTENT}")
endif()

set(ZLIB_ZUTIL_FILE "${OPENRCC_GRPC_SOURCE_DIR}/third_party/zlib/zutil.h")
if(NOT EXISTS "${ZLIB_ZUTIL_FILE}")
    message(FATAL_ERROR "zlib zutil.h not found: ${ZLIB_ZUTIL_FILE}")
endif()

file(READ "${ZLIB_ZUTIL_FILE}" ZLIB_ZUTIL_CONTENT)
set(ZLIB_OLD_CONDITION "#if defined(MACOS) || defined(TARGET_OS_MAC)")
set(ZLIB_NEW_CONDITION "#if (defined(MACOS) || defined(TARGET_OS_MAC)) && !defined(__APPLE__)")

string(FIND "${ZLIB_ZUTIL_CONTENT}" "${ZLIB_NEW_CONDITION}" ZLIB_ALREADY_PATCHED)
if(ZLIB_ALREADY_PATCHED LESS 0)
    string(FIND "${ZLIB_ZUTIL_CONTENT}" "${ZLIB_OLD_CONDITION}" ZLIB_CONDITION_OFFSET)
    if(ZLIB_CONDITION_OFFSET LESS 0)
        message(FATAL_ERROR "Expected zlib macOS compatibility condition not found in ${ZLIB_ZUTIL_FILE}")
    endif()

    string(REPLACE "${ZLIB_OLD_CONDITION}" "${ZLIB_NEW_CONDITION}" ZLIB_ZUTIL_CONTENT "${ZLIB_ZUTIL_CONTENT}")
    file(WRITE "${ZLIB_ZUTIL_FILE}" "${ZLIB_ZUTIL_CONTENT}")
endif()
